<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<c:set var="navBase" value="admin"/><c:set var="navRole" value="Admin"/><c:set var="activeNav" value="dashboard"/><c:set var="pageTitle" value="Admin Dashboard"/><c:set var="pageSubtitle" value="Platform health, approvals, and service activity."/>
<!doctype html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Admin Dashboard - QuickFix</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/style.css"><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/forms.css"><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/dashboard.css"></head>
<body><div class="app-shell"><%@ include file="../includes/sidebar.jspf" %><main><%@ include file="../includes/topbar.jspf" %><section class="page">
    <header class="page__header"><div><p class="page__eyebrow">Operations</p><h1 class="page__title">Admin dashboard</h1><p class="page__description">Monitor users, providers, bookings, complaints, and reports.</p></div><a class="btn btn--primary" href="reports">View reports</a></header>
    <div class="metric-grid"><article class="card metric-card"><p class="metric-card__label">Total users</p><p class="metric-card__value">${report.totalUsers}</p></article><article class="card metric-card"><p class="metric-card__label">Total bookings</p><p class="metric-card__value">${report.totalBookings}</p></article><article class="card metric-card"><p class="metric-card__label">Active providers</p><p class="metric-card__value">${report.activeProviders}</p></article></div>
    <div class="content-grid content-grid--two"><section class="card"><div class="card__header"><h2 class="card__title">Booking mix</h2></div><div class="card__body chart-bars"><div class="chart-bar"><span>Pending</span><span class="chart-bar__track"><span class="chart-bar__fill chart-bar__fill--42"></span></span><span>42%</span></div><div class="chart-bar"><span>Accepted</span><span class="chart-bar__track"><span class="chart-bar__fill chart-bar__fill--31"></span></span><span>31%</span></div><div class="chart-bar"><span>Completed</span><span class="chart-bar__track"><span class="chart-bar__fill chart-bar__fill--27"></span></span><span>27%</span></div></div></section><aside class="card"><div class="card__header"><h2 class="card__title">Activity</h2></div><div class="card__body activity-list"><article class="list-item"><p class="list-item__title">Provider reviews pending</p><p class="list-meta">Use Manage Providers to approve or reject verification.</p></article><article class="list-item"><p class="list-item__title">Complaints require follow-up</p><p class="list-meta">Update statuses from the complaints page.</p></article></div></aside></div>
</section></main></div></body>
</html>
