<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<c:set var="activeNav" value="feedback"/>
<!doctype html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Feedback - QuickFix</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/style.css"><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/forms.css"></head>
<body class="market-page"><%@ include file="../includes/customer-navbar.jspf" %><main class="market-main"><div class="container">
    <section class="market-two-column"><article class="card"><div class="card__header"><h1 class="card__title">Rate your service</h1></div><c:choose><c:when test="${not empty bookings}"><form class="card__body form" method="post" action="${pageContext.request.contextPath}/feedback"><label class="field"><span class="field__label">Booking</span><select class="field__control" name="bookingId"><c:forEach items="${bookings}" var="b"><option value="${b.bookingId}" data-provider="${b.providerId}">${b.serviceTitle} - ${b.providerName}</option></c:forEach></select></label><input type="hidden" name="providerId"><div class="field"><span class="field__label">Star rating</span><div class="star-input"><input id="star5" type="radio" name="rating" value="5"><label for="star5">★</label><input id="star4" type="radio" name="rating" value="4"><label for="star4">★</label><input id="star3" type="radio" name="rating" value="3"><label for="star3">★</label><input id="star2" type="radio" name="rating" value="2"><label for="star2">★</label><input id="star1" type="radio" name="rating" value="1" required><label for="star1">★</label></div></div><label class="field"><span class="field__label">Feedback</span><textarea class="field__control" name="comments" placeholder="Tell us about the service quality"></textarea></label><button class="btn btn--primary" type="submit">Submit Feedback</button></form></c:when><c:otherwise><div class="card__body"><div class="empty-state">Completed bookings will appear here for review.</div></div></c:otherwise></c:choose></article><aside class="card card__body"><h2>Provider summary</h2><p>Select a completed booking and submit your review.</p></aside></section>
</div></main></body>
</html>
