<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<c:set var="navBase" value="provider"/><c:set var="navRole" value="Provider"/><c:set var="activeNav" value="availability"/><c:set var="pageTitle" value="Availability"/><c:set var="pageSubtitle" value="Publish working slots customers can request."/>
<!doctype html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Availability - QuickFix</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/style.css"><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/forms.css"><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/dashboard.css"></head>
<body><div class="app-shell"><%@ include file="../includes/sidebar.jspf" %><main><%@ include file="../includes/topbar.jspf" %><section class="page">
    <div class="content-grid">
        <section class="card"><div class="card__header"><h1 class="card__title">Add availability</h1></div><form class="card__body form" method="post"><input type="hidden" name="action" value="availability"><div class="form__grid"><label class="field"><span class="field__label">Date</span><input class="field__control" type="date" name="availableDate" required></label><label class="field"><span class="field__label">Start time</span><input class="field__control" type="time" name="startTime" required></label><label class="field"><span class="field__label">End time</span><input class="field__control" type="time" name="endTime" required></label></div><button class="btn btn--primary" type="submit">Add slot</button></form></section>
        <section class="card"><div class="card__header"><h2 class="card__title">Weekly grid</h2></div><div class="card__body availability-grid"><div class="availability-day"><div class="availability-day__name">Mon</div></div><div class="availability-day"><div class="availability-day__name">Tue</div></div><div class="availability-day"><div class="availability-day__name">Wed</div></div><div class="availability-day"><div class="availability-day__name">Thu</div></div><div class="availability-day"><div class="availability-day__name">Fri</div></div><div class="availability-day"><div class="availability-day__name">Sat</div></div><div class="availability-day"><div class="availability-day__name">Sun</div></div></div></section>
        <section class="card table-card"><div class="card__header"><h2 class="card__title">Saved slots</h2></div><table class="table"><thead><tr><th>Date</th><th>Start</th><th>End</th></tr></thead><tbody><c:forEach items="${availability}" var="a"><tr><td>${a.availableDate}</td><td>${a.startTime}</td><td>${a.endTime}</td></tr></c:forEach></tbody></table></section>
    </div>
</section></main></div></body>
</html>
